# Generated by Django 5.0.6 on 2024-06-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='ProductName')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
            ],
        ),
    ]
