# Generated by Django 5.0.6 on 2024-06-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_remove_version_applink_version_macoslink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='LinPortLink',
        ),
        migrations.RemoveField(
            model_name='version',
            name='LinRPMLink',
        ),
        migrations.RemoveField(
            model_name='version',
            name='MacOsLink',
        ),
        migrations.RemoveField(
            model_name='version',
            name='WinExeLink',
        ),
        migrations.RemoveField(
            model_name='version',
            name='WinMsiLink',
        ),
        migrations.AddField(
            model_name='version',
            name='linPortLink',
            field=models.CharField(max_length=50, null=True, verbose_name='Linux_Version_Portable'),
        ),
        migrations.AddField(
            model_name='version',
            name='linRPMLink',
            field=models.CharField(max_length=50, null=True, verbose_name='Linux_Version_RPM'),
        ),
        migrations.AddField(
            model_name='version',
            name='macOsLink',
            field=models.CharField(max_length=50, null=True, verbose_name='MacOs_Version'),
        ),
        migrations.AddField(
            model_name='version',
            name='winExeLink',
            field=models.CharField(max_length=50, null=True, verbose_name='Windows_Version_Exe'),
        ),
        migrations.AddField(
            model_name='version',
            name='winMsiLink',
            field=models.CharField(max_length=50, null=True, verbose_name='Windows_Version_MSI'),
        ),
    ]
