# Generated by Django 5.0.6 on 2024-06-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_remove_version_linportlink_remove_version_linrpmlink_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Название'},
        ),
    ]
