# Generated by Django 5.0.6 on 2024-06-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'Версия продукта', 'verbose_name_plural': 'Версии продуктов'},
        ),
    ]
