# Generated by Django 5.0.6 on 2024-06-14 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_rename_linportlink_version_linportink_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='linPortink',
            new_name='linPorlink',
        ),
    ]
