# Generated by Django 5.0.6 on 2024-06-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_rename_linportink_version_linporlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='linPorlink',
            new_name='linPortlink',
        ),
    ]
