# Generated by Django 5.0.6 on 2024-06-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_rename_linporlink_version_linportlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='linPortlink',
        ),
        migrations.RemoveField(
            model_name='version',
            name='linRPMlink',
        ),
        migrations.RemoveField(
            model_name='version',
            name='macOslink',
        ),
        migrations.RemoveField(
            model_name='version',
            name='winExelink',
        ),
        migrations.RemoveField(
            model_name='version',
            name='winMsilink',
        ),
        migrations.AlterField(
            model_name='version',
            name='version',
            field=models.CharField(default=0, max_length=50, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='version',
            name='linPortLink',
            field=models.CharField(default=0, max_length=50, verbose_name='Linux_Version_Portable'),
        ),
        migrations.AddField(
            model_name='version',
            name='linRPMLink',
            field=models.CharField(default=0, max_length=50, verbose_name='Linux_Version_RPM'),
        ),
        migrations.AddField(
            model_name='version',
            name='macOsLink',
            field=models.CharField(default=0, max_length=50, verbose_name='MacOs_Version'),
        ),
        migrations.AddField(
            model_name='version',
            name='winExeLink',
            field=models.CharField(default=0, max_length=50, verbose_name='Windows_Version_Exe'),
        ),
        migrations.AddField(
            model_name='version',
            name='winMsiLink',
            field=models.CharField(default=0, max_length=50, verbose_name='Windows_Version_MSI'),
        ),
    ]
