# Generated by Django 5.0.6 on 2024-06-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_remove_version_linportlink_remove_version_linrpmlink_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='linPortLink',
            new_name='lin_port_link',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='linRPMLink',
            new_name='lin_rpm_link',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='macOsLink',
            new_name='mac_os_link',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='winExeLink',
            new_name='win_exe_link',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='winMsiLink',
            new_name='win_msi_link',
        ),
    ]
