# Generated by Django 5.0.6 on 2024-07-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_rename_linportlink_version_lin_port_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'Product Version', 'verbose_name_plural': 'Product Versions'},
        ),
        migrations.RemoveField(
            model_name='version',
            name='lin_port_link',
        ),
        migrations.RemoveField(
            model_name='version',
            name='lin_rpm_link',
        ),
        migrations.RemoveField(
            model_name='version',
            name='win_exe_link',
        ),
        migrations.RemoveField(
            model_name='version',
            name='win_msi_link',
        ),
        migrations.AddField(
            model_name='version',
            name='linux_portable_link',
            field=models.CharField(default=0, max_length=50, verbose_name='Linux_Portable_Version'),
        ),
        migrations.AddField(
            model_name='version',
            name='linux_rpm_link',
            field=models.CharField(default=0, max_length=50, verbose_name='Linux_RPM_Version'),
        ),
        migrations.AddField(
            model_name='version',
            name='windows_exe_link',
            field=models.CharField(default=0, max_length=50, verbose_name='Windows_Exe_Version'),
        ),
        migrations.AddField(
            model_name='version',
            name='windows_msi_link',
            field=models.CharField(default=0, max_length=50, verbose_name='Windows_MSI_Version'),
        ),
        migrations.AlterField(
            model_name='version',
            name='mac_os_link',
            field=models.CharField(default=0, max_length=50, verbose_name='Mac_Os_Version'),
        ),
    ]
